/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const InstagramEntry = IDL.Record({
  'id' : IDL.Nat,
  'pin' : IDL.Nat,
  'area' : IDL.Text,
  'name' : IDL.Text,
  'instagramUsername' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'addEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'deleteEntry' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'getAllEntries' : IDL.Func([], [IDL.Vec(InstagramEntry)], ['query']),
  'getEntriesByArea' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(InstagramEntry)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const InstagramEntry = IDL.Record({
    'id' : IDL.Nat,
    'pin' : IDL.Nat,
    'area' : IDL.Text,
    'name' : IDL.Text,
    'instagramUsername' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'addEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'deleteEntry' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'getAllEntries' : IDL.Func([], [IDL.Vec(InstagramEntry)], ['query']),
    'getEntriesByArea' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(InstagramEntry)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };